export const ICON_TYPES = {
    arrowLeft: "arrowLeft",
    info: "info",
    card: "card",
    settings: "settings",
    web: "web",
    unlimited_calls: "unlimited_calls",
    other_calls: "other_calls",
    wifi: "wifi",
    sim: "sim",
    wallet: "wallet",
    sms: "sms",
    collapsedArrow: "collapsedArrow",
    radioUnchecked: "radioUnchecked",
    radioChecked: "radioChecked",
    pdf: "pdf",
    pen: "pen",
    cross: "cross",
    checkboxUnchecked: "checkboxUnchecked",
    checkboxChecked: "checkboxChecked",
    share: "share",
    download: "download",
    check: "check",
    collapsedPlus: "collapsedPlus",
    collapsedMinus: "collapsedMinus",
    googlePlay: "googlePlay",
    appStore: "appStore",
    retry: "retry",
    star: "star",
    calendar: "calendar",
    global: "global",
    price_plan: "price_plan",
    arrowRight: "arrowRight",
    extraServices: "extraServices",
    clock: "clock",
} as const
export type TIconType = keyof typeof ICON_TYPES;